var fs = require('fs');
var faker = require('faker');
var pdf = require('html-pdf');

function createDirectoryChildren(src){
  // random logic: which files and how many?
  var directory = [];
  var file, type, name;

  // How many files?
  var count = faker.random.number({min: 1, max: 5});

  var words = [
    "AFM",
    "AMLC",
    "A0/1C",
    "BES",
    "BFT",
    "BOOM",
    "BVI",
    "CJIB",
    "CN",
    "CTE/PF",
    "CT",
    "Infobox",
    "CWI",
    "DLR",
    "DNB",
    "DWI",
    "EC",
    "EMM",
    "EMPACT",
    "ESW",
    "EU",
    "FAT",
    "F",
    "FEC",
    "FinEC",
    "FIU",
    "FIOD",
    "FP",
    "GoAML",
    "iCOV",
    "ILT/IOD",
    "Autoriteit",
    "FinanciÃ«le",
    "Markten",
    "Anti",
    "Money",
    "Laundering",
    "Centre,",
    "onderdeel",
    "van",
    "de",
    "FIOD",
    "Administratieve",
    "organisatie",
    "en",
    "interne",
    "controle",
    "de",
    "BES",
    "eilanden",
    "van",
    "Caribisch",
    "Nederland:",
    "Bonaire.",
    "Sint",
    "Eustatiusen",
    "Saba",
    "Bureau",
    "Financieel",
    "Toezicht",
    "Bureau",
    "Ontnemingswetgeving",
    "Openbaar",
    "Ministerie,",
    "Basisvoorziening",
    "Informatie,",
    "een",
    "applicatie",
    "van",
    "de",
    "politie",
    "Centraal",
    "Justitieel",
    "Incasso",
    "Bureau",
    "Caribisch",
    "Nederland",
    "Contraterrorisme",
    "&",
    "proliferatiefmanciering.",
    "een",
    "team",
    "binnen",
    "de",
    "FlU-Nederland",
    "Contraterrorisme",
    "Infobox",
    "Cluster",
    "Werk",
    "en",
    "Inkomen,",
    "onderdeel",
    "van",
    "de",
    "gemeente",
    "Rotterdam",
    "Dienst",
    "Landelijke",
    "Recherche,",
    "onderdeel",
    "van",
    "de",
    "Landelijke",
    "Eenheid",
    "van",
    "de",
    "politie",
    "De",
    "Nederlandsche",
    "Bank",
    "Dienst",
    "Werk",
    "en",
    "Inkomen,",
    "onderdeel",
    "van",
    "de",
    "gemeente",
    "Amsterdam",
    "Europese",
    "Commissie,",
    "uitvoerend",
    "orgaan",
    "van",
    "de",
    "EU",
    "Expertisecentrum",
    "Mensenhandel",
    "en",
    "Mensensmokkel",
    "European",
    "Multidisciplinary",
    "Platform",
    "Against",
    "Criminal",
    "Europese",
    "Unie",
    "Financial",
    "Action",
    "Task",
    "Force",
    "Financieel",
    "Expertise",
    "Centrum",
    "Programma",
    "Financieel",
    "Economische",
    "Criminaliteit",
    "Financial",
    "Intelligence",
    "Unit",
    "Fiscale",
    "Inlichtingen-",
    "en",
    "Opsporingsdienst",
    "Functioneel",
    "Parket,",
    "onderdeel",
    "van",
    "het",
    "OM",
    "Government",
    "Anti-Money",
    "Laundering.",
    "ICT",
    "applicatie",
    "gebouwd",
    "door",
    "UNODC",
    "Infobox",
    "Crimineel",
    "en",
    "Onverklaarbaar",
    "Vermogen",
    "Inspectie",
    "Leefomgeving",
    "en",
    "Transport",
    "/",
    "Inlichtingen-",
    "en",
    "Opsporingsdienst",
    "Andrea",
    "Andrea",
    "andrea",
    "andrea"
  ];

  for (var i = 0; i < count; i++){
    type = faker.random.arrayElement(['txt', 'txt', 'pdf']);

    name = faker.random.arrayElement(words) + "_" + faker.random.arrayElement(words) + "." + type;
    name = name.replace(/\//, '');

    path = JSON.parse(JSON.stringify(src));
    path.push(name);

    file = {
      name: name,
      path: path,
      type: type
    }
    
    // create meta-data
    directory.push(file);
  }

  return directory;
}

module.exports = createDirectoryChildren;